# Generated by Django 4.0.3 on 2022-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eid', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
